development:
  adapter: mysql2
  encoding: utf8mb4
  database: gogo_development
  host: localhost
  username: root
  password: 1123

test:
  adapter: mysql2
  encoding: utf8mb4
  database: gogo_test
  host: localhost
  username: root
  password: 1123

production:
  adapter: mysql2
  encoding: utf8mb4
  database: gogo_production
  host: localhost
  username: root
  password: 1123
